version: "3"
services:
  front:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./front/:/code
      - ./conf/front.conf:/etc/nginx/conf.d/default.conf
    links:
      - back
  back:
    build:
      context: ./conf
      dockerfile: back.dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.30 remote_port=9090 remote_enable=1
    volumes:
      - ./back:/code
      - ./conf/dsn.ini:/usr/local/etc/php/conf.d/dsn.ini
      - ./logs:/var/log/testcase
    links:
      - db
  db:
    image: postgres:9.6
    # ports:
    #   - "5437:5432"
    volumes:
      - ./conf/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"